#!/bin/bash

ROOT=$(git rev-parse --show-toplevel)
pushd "$ROOT"
rm -rf docs
mkdir -p docs
swift package --allow-writing-to-directory ./docs \
    generate-documentation --target StateTree \
    --disable-indexing \
    --transform-for-static-hosting \
    --output-path ./docs

popd


# http://localhost:3000/documentation/statetree
# --hosting-base-path StateTree \
